[user]
name = "Ivan Perdomo"
email = "iperdomo2016@gmail.com"

[ui]
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
diff-formatter = ["difft", "--color=always", "$left", "$right"]

[git]
private-commits = "description(glob: 'wip:*') | description(glob:'private:*')"
push-new-bookmarks = true
